## Hands-on Exercises / Tasks

#### Exercise 1:
Create a 5×5 identity matrix.

In [1]:
import numpy as np

identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


#### Exercise 2:
Generate random marks for 10 students in 3 subjects. Find average per student.


In [2]:
import numpy as np

marks = np.random.randint(0, 101, (10, 3))
average_per_student = np.mean(marks, axis=1)

marks, average_per_student

(array([[ 9, 44, 42],
        [64,  1, 57],
        [88, 92, 51],
        [70, 60, 91],
        [79,  7, 83],
        [60, 99, 83],
        [44, 84, 17],
        [34, 57, 39],
        [58, 34, 53],
        [27, 37, 37]], dtype=int32),
 array([31.66666667, 40.66666667, 77.        , 73.66666667, 56.33333333,
        80.66666667, 48.33333333, 43.33333333, 48.33333333, 33.66666667]))

#### Exercise 3:
Convert temperatures [0, 10, 20, 30] °C to Fahrenheit using formula F = C * 9/5 + 32.

In [3]:
import numpy as np

celsius = np.array([0, 10, 20, 30])
fahrenheit = celsius * 9 / 5 + 32

fahrenheit

array([32., 50., 68., 86.])

#### Exercise 4:
Create an array of zeros (4×4) and replace diagonal with 1, 2, 3, 4.

In [4]:
import numpy as np

arr = np.zeros((4, 4))
np.fill_diagonal(arr, [1, 2, 3, 4])

arr

array([[1., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 3., 0.],
       [0., 0., 0., 4.]])

#### Exercise 5:
Simulate monthly revenue for 12 months and find: total revenue, best month, worst month.`m

In [5]:
import numpy as np

# Simulate monthly revenue (e.g., random integers between 50k and 150k)
revenue = np.random.randint(50000, 150001, size=12)

total_revenue = revenue.sum()
best_month = revenue.argmax()  # index of max revenue (0-based)
worst_month = revenue.argmin() # index of min revenue (0-based)

revenue, total_revenue, best_month, worst_month

(array([129126, 114921, 114391,  59891, 109843,  89568,  90149, 105601,
         80884,  81464, 115041,  74986], dtype=int32),
 np.int64(1165865),
 np.int64(0),
 np.int64(3))

#### Exercise 6:
Create two arrays of size 2×3 and add them using broadcasting.

In [6]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([[10, 20, 30],
              [40, 50, 60]])

result = a + b
result

array([[11, 22, 33],
       [44, 55, 66]])

#### Exercise 7:
From an array [10,20,30,40,50,60], pick all elements >30 using Boolean indexing.

In [7]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])
result = arr[arr > 30]

result

array([40, 50, 60])

#### Exercise 8:
Reshape an array of numbers 0–11 into a 3×4 matrix, then flatten it.

In [8]:
import numpy as np

arr = np.arange(12).reshape(3, 4)
flattened = arr.flatten()

arr, flattened

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]))

#### Exercise 9:
Create a random 2×5 array, compute sum, mean, max, min along rows and columns.

In [9]:
import numpy as np

arr = np.random.rand(2, 5)

row_sum = arr.sum(axis=1)
col_sum = arr.sum(axis=0)

row_mean = arr.mean(axis=1)
col_mean = arr.mean(axis=0)

row_max = arr.max(axis=1)
col_max = arr.max(axis=0)

row_min = arr.min(axis=1)
col_min = arr.min(axis=0)

arr, row_sum, col_sum, row_mean, col_mean, row_max, col_max, row_min, col_min

(array([[0.36202802, 0.42182668, 0.95155646, 0.60333917, 0.5058125 ],
        [0.11882888, 0.88217845, 0.4505905 , 0.71655997, 0.60120444]]),
 array([2.84456283, 2.76936224]),
 array([0.48085691, 1.30400513, 1.40214696, 1.31989914, 1.10701694]),
 array([0.56891257, 0.55387245]),
 array([0.24042845, 0.65200256, 0.70107348, 0.65994957, 0.55350847]),
 array([0.95155646, 0.88217845]),
 array([0.36202802, 0.88217845, 0.95155646, 0.71655997, 0.60120444]),
 array([0.36202802, 0.11882888]),
 array([0.11882888, 0.42182668, 0.4505905 , 0.60333917, 0.5058125 ]))

#### Exercise 10:
Simulate 3 years of daily temperatures (3×365), compute average temperature per year.

In [10]:
import numpy as np

temps = np.random.uniform(low=-10, high=40, size=(3, 365))
avg_per_year = temps.mean(axis=1)

temps, avg_per_year

(array([[23.55308316, 18.54588713, 26.94777886, ..., 26.92730625,
         27.87651965, 33.85305997],
        [ 5.7559409 , 10.65121726, -1.53359517, ..., 13.64072923,
         17.46012266, 24.4157649 ],
        [27.08024184, 24.4507139 , 19.35852176, ..., 27.10861885,
          8.20591374, 39.76817944]], shape=(3, 365)),
 array([14.48864225, 16.03994627, 15.50175232]))